[project]
name = "molmo-spaces-maniskill"
version = "0.0.1"
description = "ManiSkill environments for ProcTHOR and RoboTHOR"
readme = "README.md"
authors = []
requires-python = ">=3.10"
dependencies = [
    "mani-skill @ git+https://github.com/wpumacay/ManiSkill.git@dev-molmospaces",
    "mujoco",
    "tyro",
    "msgspec",
    "setuptools==80.8.0",
    "lmdb~=1.7.5",
    "zstandard~=0.25.0",
]

[build-system]
requires = ["uv_build>=0.8.6,<0.9.0"]
build-backend = "uv_build"

[project.optional-dependencies]
dev = [
    "pre-commit",
    "pybind11-stubgen",
    "ruff",
    "ty",
    "ipython",
]

[project.scripts]
ms-download = "molmo_spaces_maniskill.downloader.main:main"

[tool.ruff]
target-version = "py310"
line-length = 100

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
docstring-code-format = false

[tool.ruff.lint]
select = [
    # # docstring
    # "D",
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # PEP8
    "W",
    # Pylint
    "PL",
]
ignore = [
    "C408",    # dict() calls
    "C901",    # function complexity
    "E501",    # line too long (handled by line-length setting)
    "B006",    # defaults shouldn't be mutable
    "UP015",   # redundant mode arguments in open should be fine for now
    "SIM117",  # allow nested with statements for now
    "SIM102",  # don't be picky about nested if statements
    "SIM114",  # don't be picky about merging if branches using or
    "PLR0912",
    "PLR0913",
    "PLR0915",
    "PLC0415",
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ty.environment]
extra-paths = ["./typings"]

[tool.pyright]
stubPath = "./typings"
